### ISSUE TITLE
Suggestion: clarify what this tool does and doesn't prove

### ISSUE THREAD

**Issue by JohnRusk** [evenh/az-blob-hashdeep#2]
Hi, I was delighted to be introduced to az-blob-hashdeep today.  I've been wanting to be able to point our AzCopy users to a tool like this.

One suggestion, could you clarify in the documentation what it does, and doesn't prove, when it downloads an existing Content MD5 hash. Specifically, that does not actually prove that the blob content matches the hash.

I posted a description of the issues, with a tip on checking blob content, here in response to an AzCopy issue: https://github.com/Azure/azure-storage-azcopy/issues/715#issuecomment-556341537 . Could you take a look, and may add a few notes to az-blob-hashdeep's home page?  So that users can understand what it does, and doesn't prove. Also, you're welcome to describe or refer to the AzCopy-download-to-null trick, as a way of checking actual blob content.

**Comment by evenh** [comment]
Thanks for reaching out John. I'm happy you find the tool useful :-)

I will update the documentation with your suggestion and when I do get some spare time I plan to implement the download-to-null trick 👍.

**Comment by evenh** [comment]
I know that you're working on AKS now @JohnRusk but wanted to let you know that as of `v1.3.0`, the tool now actually downloads the contents to memory and calculates the MD5 digest by itself, without depending on Azure Blob Storage metadata. The natural continuation will now be #24.
